services:
  redis:
    image: redis
    build:
      context: .
      dockerfile: redis/Dockerfile
    container_name: redis
    ports:
      - 6379:50000
    command: redis-server /etc/redis.conf
  prometheus:
    image: prom/prometheus
    build:
      context: .
      dockerfile: prometheus/Dockerfile
    container_name: prometheus
    ports:
      - 9090:9090
